ojo_job_count: 100
evaluation_results_path: "outputs/evaluation/aggregate_ojo_esco/ojo_esco_occupation_skills_results.json"
esco_path: "inputs/data/esco/"
esco_data_dir: 'escoe_extension/inputs/data/esco/'